# Generated by Django 3.2.8 on 2021-11-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostock', '0005_auto_20211104_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Картинка'),
        ),
    ]
