# Generated by Django 3.2.8 on 2021-11-18 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photostock', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='email',
            field=models.EmailField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=100, verbose_name='Почта'),
        ),
    ]
